package com.dmt.toeicapp.chatbot.service.impl;

import com.dmt.toeicapp.common.exception.AppException;
import com.dmt.toeicapp.common.security.SecurityUtils;
import com.dmt.toeicapp.common.util.GeminiAiService;
import com.dmt.toeicapp.flashcard.entity.Flashcard;
import com.dmt.toeicapp.flashcard.repository.FlashcardRepository;
import com.dmt.toeicapp.i18n.entity.FlashcardTranslation;
import com.dmt.toeicapp.i18n.entity.TopicTranslation;
import com.dmt.toeicapp.i18n.repository.FlashcardTranslationRepository;
import com.dmt.toeicapp.i18n.repository.TopicTranslationRepository;
import com.dmt.toeicapp.chatbot.dto.AiMultiLangTopicResponse;
import com.dmt.toeicapp.topic.dto.TopicResponse;
import com.dmt.toeicapp.topic.entity.Topic;
import com.dmt.toeicapp.topic.mapper.TopicMapper;
import com.dmt.toeicapp.topic.repository.TopicRepository;
import com.dmt.toeicapp.chatbot.service.AiTopicService;
import com.dmt.toeicapp.common.constant.AppConstants;
import com.dmt.toeicapp.user.entity.User;
import com.dmt.toeicapp.user.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Map;

@Service
@RequiredArgsConstructor
public class AiTopicServiceImpl implements AiTopicService {

    private final GeminiAiService geminiAiService;
    private final TopicRepository topicRepository;
    private final TopicTranslationRepository topicTranslationRepository;
    private final FlashcardRepository flashcardRepository;
    private final FlashcardTranslationRepository flashcardTranslationRepository;
    private final UserRepository userRepository;
    private final TopicMapper topicMapper;



    @Override
    @Transactional
    public TopicResponse generateAndSaveTopic(String userRequest) {
        // 1. Lấy thông tin user đăng nhập hiện tại
        Long currentUserId = SecurityUtils.getCurrentUserId();
        User currentUser = userRepository.findById(currentUserId)
                .orElseThrow(() -> AppException.notFound("Không tìm thấy người dùng hiện tại."));

        // 2. Gọi AI tạo dữ liệu đa ngôn ngữ
        AiMultiLangTopicResponse aiResponse = geminiAiService.generateMultiLangTopic(userRequest);

        // 3. Phân tách phần dữ liệu gốc tiếng Anh (en) cho thực thể cha
        AiMultiLangTopicResponse.TopicTranslationItem enTopic = aiResponse.topicTranslations().stream()
                .filter(t -> AppConstants.DEFAULT_LOCALE.equalsIgnoreCase(t.locale()))
                .findFirst()
                .orElse(null);
        if (enTopic == null) {
            // Trường hợp hy hữu AI thiếu bản dịch en, dùng bất kỳ ngôn ngữ nào có sẵn làm mặc định
            enTopic = aiResponse.topicTranslations().stream().findFirst()
                    .orElse(new AiMultiLangTopicResponse.TopicTranslationItem(AppConstants.DEFAULT_LOCALE, "AI Generated Topic", "Generated by AI"));
        }

        // 4. Lưu Topic gốc (tiếng Anh)
        Topic topic = Topic.builder()
                .name(enTopic.name())
                .description(enTopic.description())
                .createdBy(currentUser)
                .system(false) // Mặc định là cá nhân, không phải system
                .build();
        topic = topicRepository.save(topic);

        // 5. Lưu các bản dịch Topic sang các ngôn ngữ khác (vi, ja, ko)
        for (AiMultiLangTopicResponse.TopicTranslationItem entry : aiResponse.topicTranslations()) {
            String locale = entry.locale();
            if (AppConstants.DEFAULT_LOCALE.equalsIgnoreCase(locale)) continue; // Bỏ qua tiếng Anh vì đã lưu ở bảng cha

            TopicTranslation topicTranslation = TopicTranslation.builder()
                    .topic(topic)
                    .locale(locale)
                    .name(entry.name())
                    .description(entry.description())
                    .build();
            topicTranslationRepository.save(topicTranslation);
        }

        // 6. Duyệt và lưu Flashcards
        for (AiMultiLangTopicResponse.AiMultiLangFlashcardItem cardItem : aiResponse.flashcards()) {
            AiMultiLangTopicResponse.FlashcardTranslationItem enCard = cardItem.flashcardTranslations().stream()
                    .filter(c -> AppConstants.DEFAULT_LOCALE.equalsIgnoreCase(c.locale()))
                    .findFirst()
                    .orElse(null);
            if (enCard == null) {
                enCard = cardItem.flashcardTranslations().stream().findFirst()
                        .orElse(new AiMultiLangTopicResponse.FlashcardTranslationItem(AppConstants.DEFAULT_LOCALE, "Definition not provided", "Example not provided"));
            }

            // Lưu Flashcard gốc (tiếng Anh)
            Flashcard flashcard = Flashcard.builder()
                    .topic(topic)
                    .createdBy(currentUser)
                    .word(cardItem.word())
                    .pronunciation(cardItem.pronunciation())
                    .definition(enCard.definition())
                    .exampleSentence(enCard.exampleSentence())
                    .active(true)
                    .build();
            flashcard = flashcardRepository.save(flashcard);

            // Lưu các bản dịch Flashcard sang các ngôn ngữ khác (vi, ja, ko)
            for (AiMultiLangTopicResponse.FlashcardTranslationItem entry : cardItem.flashcardTranslations()) {
                String locale = entry.locale();
                if (AppConstants.DEFAULT_LOCALE.equalsIgnoreCase(locale)) continue; // Bỏ qua tiếng Anh

                FlashcardTranslation cardTranslation = FlashcardTranslation.builder()
                        .flashcard(flashcard)
                        .locale(locale)
                        .definition(entry.definition())
                        .exampleSentence(entry.exampleSentence())
                        .createdBy(currentUser)
                        .build();
                flashcardTranslationRepository.save(cardTranslation);
            }
        }

        // 7. Trả về thông tin Topic vừa tạo dưới dạng mặc định (tiếng Anh)
        return topicMapper.toResponse(topic);
    }
}