package com.dmt.toeicapp.chatbot.service.impl;

import com.dmt.toeicapp.chatbot.dto.AiMultiLangTopicResponse;
import com.dmt.toeicapp.chatbot.dto.EnrichedFlashcardItem;
import com.dmt.toeicapp.chatbot.service.AiTopicPersistenceService;
import com.dmt.toeicapp.common.constant.AppConstants;
import com.dmt.toeicapp.external.dictionary.WordEnrichmentResult;
import com.dmt.toeicapp.flashcard.entity.Flashcard;
import com.dmt.toeicapp.flashcard.repository.FlashcardRepository;
import com.dmt.toeicapp.flashcard.service.DatamuseEnrichmentService;
import com.dmt.toeicapp.i18n.entity.FlashcardTranslation;
import com.dmt.toeicapp.i18n.entity.TopicTranslation;
import com.dmt.toeicapp.i18n.repository.FlashcardTranslationRepository;
import com.dmt.toeicapp.i18n.repository.TopicTranslationRepository;
import com.dmt.toeicapp.topic.dto.TopicResponse;
import com.dmt.toeicapp.topic.entity.Topic;
import com.dmt.toeicapp.topic.mapper.TopicMapper;
import com.dmt.toeicapp.topic.repository.TopicRepository;
import com.dmt.toeicapp.user.entity.User;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;

import java.util.List;

@Service
@Slf4j
@RequiredArgsConstructor
public class AiTopicPersistenceServiceImpl implements AiTopicPersistenceService {

    private final TopicRepository                topicRepository;
    private final TopicTranslationRepository     topicTranslationRepository;
    private final FlashcardRepository            flashcardRepository;
    private final FlashcardTranslationRepository flashcardTranslationRepository;
    private final TopicMapper                    topicMapper;
    private final DatamuseEnrichmentService      datamuseEnrichmentService;

    @Override
    @Transactional
    public TopicResponse saveAll(User owner,
                                 AiMultiLangTopicResponse aiResponse,
                                 List<EnrichedFlashcardItem> enrichedItems) {

        // 1. Lấy bản dịch tiếng Anh làm dữ liệu chính cho Topic
        AiMultiLangTopicResponse.TopicTranslationItem enTopic = aiResponse.topicTranslations().stream()
                .filter(t -> AppConstants.DEFAULT_LOCALE.equalsIgnoreCase(t.locale()))
                .findFirst()
                .orElseGet(() -> aiResponse.topicTranslations().stream().findFirst()
                        .orElse(new AiMultiLangTopicResponse.TopicTranslationItem(
                                AppConstants.DEFAULT_LOCALE, "AI Generated Topic", "Generated by AI")));

        // 2. Lưu Topic gốc (tiếng Anh)
        Topic topic = Topic.builder()
                .name(enTopic.name())
                .description(enTopic.description())
                .createdBy(owner)
                .system(false)
                .build();
        topic = topicRepository.save(topic);
        log.debug("Saved topic '{}' (id={})", topic.getName(), topic.getId());

        // 3. Lưu các bản dịch Topic (vi, ja, ko...)
        for (AiMultiLangTopicResponse.TopicTranslationItem entry : aiResponse.topicTranslations()) {
            if (AppConstants.DEFAULT_LOCALE.equalsIgnoreCase(entry.locale())) continue;

            TopicTranslation topicTranslation = TopicTranslation.builder()
                    .topic(topic)
                    .locale(entry.locale())
                    .name(entry.name())
                    .description(entry.description())
                    .build();
            topicTranslationRepository.save(topicTranslation);
        }

        // 4. Lưu Flashcards + Translations
        if (enrichedItems != null) {
            for (EnrichedFlashcardItem enriched : enrichedItems) {
                AiMultiLangTopicResponse.AiMultiLangFlashcardItem cardItem = enriched.cardItem();
                WordEnrichmentResult enrichment = enriched.enrichment();

                // Lấy dữ liệu tiếng Anh cho Flashcard gốc
                AiMultiLangTopicResponse.FlashcardTranslationItem enCard = cardItem.flashcardTranslations().stream()
                        .filter(c -> AppConstants.DEFAULT_LOCALE.equalsIgnoreCase(c.locale()))
                        .findFirst()
                        .orElseGet(() -> cardItem.flashcardTranslations().stream().findFirst()
                                .orElse(new AiMultiLangTopicResponse.FlashcardTranslationItem(
                                        AppConstants.DEFAULT_LOCALE, "Definition not provided", "Example not provided")));

                // Ưu tiên IPA từ Dictionary, fallback về phiên âm Gemini cung cấp
                String pronunciation = (enrichment.pronunciation() != null && !enrichment.pronunciation().isBlank())
                        ? enrichment.pronunciation()
                        : cardItem.pronunciation();

                // Lưu Flashcard gốc
                Flashcard flashcard = Flashcard.builder()
                        .topic(topic)
                        .createdBy(owner)
                        .word(cardItem.word())
                        .pronunciation(pronunciation)
                        .audioUrl(enrichment.audioUrl())
                        .partOfSpeech(enrichment.partOfSpeech())
                        .definition(enCard.definition())
                        .exampleSentence(enCard.exampleSentence())
                        .active(true)
                        .build();
                flashcard = flashcardRepository.save(flashcard);

                // Đăng ký Datamuse enrichment chạy sau khi TX commit thành công
                final Long savedCardId = flashcard.getId();
                final String savedWord = flashcard.getWord();
                if (TransactionSynchronizationManager.isSynchronizationActive()) {
                    TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization() {
                        @Override
                        public void afterCommit() {
                            datamuseEnrichmentService.enrichRelatedWordsAsync(savedCardId, savedWord);
                        }
                    });
                } else {
                    datamuseEnrichmentService.enrichRelatedWordsAsync(savedCardId, savedWord);
                }

                // Lưu các bản dịch Flashcard (vi, ja, ko...)
                for (AiMultiLangTopicResponse.FlashcardTranslationItem entry : cardItem.flashcardTranslations()) {
                    if (AppConstants.DEFAULT_LOCALE.equalsIgnoreCase(entry.locale())) continue;

                    FlashcardTranslation cardTranslation = FlashcardTranslation.builder()
                            .flashcard(flashcard)
                            .locale(entry.locale())
                            .definition(entry.definition())
                            .exampleSentence(entry.exampleSentence())
                            .createdBy(owner)
                            .build();
                    flashcardTranslationRepository.save(cardTranslation);
                }
            }
        }

        log.info("Persisted AI topic '{}' with {} flashcards for user '{}'",
                topic.getName(), enrichedItems != null ? enrichedItems.size() : 0, owner.getUsername());

        return topicMapper.toResponse(topic);
    }
}
